Repository GoogleCloudPlatform/anthos-service-mesh-packages, pull requests merged in 2021-04, with the labels that each got.

#573 Staging 1.9 asm
  asm/istio/options/hub-meshca.yaml
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#569 Kpt pkg get from tag
  scripts/asm-installer/install_asm
Labels: cla: yes

#575 Change how to retrieve environ project id (#571)
  scripts/asm-installer/install_asm
Labels: cla: yes

#562 add centos 8 support in asm_vm
  scripts/asm-installer/asm_vm
Labels: cla: yes

#568 publish the file name as SemVer
  scripts/asm-installer/release_asm_installer
Labels: cla: yes

#578 fix to earlier custom revision commit
  scripts/asm-installer/install_asm
Labels: cla: yes

#579 Avoid unbound variable error in associative array
  scripts/asm-installer/asm_vm
Labels: cla: yes

#577 Conditional required roles
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_suite_required_roles
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#582 add support for centos 7
  scripts/asm-installer/asm_vm
Labels: cla: yes

#580 add a file to display all available versions
  scripts/release-asm/common.sh
  scripts/release-asm/pre_release_backfill
  scripts/release-asm/release_asm_installer
Labels: cla: yes

#581 Installation Options for frictionless CA migration
  asm/istio/options/ca-migration-citadel.yaml
  asm/istio/options/ca-migration-meshca.yaml
Labels: cla: yes

#587 fix cleanup bug
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#586 limit the backfill to only semver files
  scripts/release-asm/common.sh
  scripts/release-asm/pre_release_backfill
Labels: cla: yes

#583 added the flag to create the namespace
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/fake_kubectl
Labels: cla: yes

#592 count "roles/container.admin" as cluster admin
  scripts/asm-installer/install_asm
Labels: cla: yes

#593 apply the validating webhook
  scripts/asm-installer/install_asm
Labels: cla: yes

#594 add function to remove duplicate image instances and template
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#596 Enable protocol detection for ASM 1.10
  asm/istio/istio-operator.yaml
Labels: cla: yes

#599 update ASM version
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#600 Update default config version in staging
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#598 add centos test
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_instance_template_creation
Labels: cla: yes

#603 Add special case for owner role
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/fake_gcloud
  scripts/asm-installer/tests/run_cli_tests
Labels: asm-installer, bug, cla: yes

#602 Always update base installation with MCP
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#605 Bump version to 1.7.8-asm.1.
  asm/Kptfile
  asm/canonical-service/controller.yaml
  asm/istio/istio-operator.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#606 Bump version to 1.8.5-asm.2
  asm/Kptfile
  asm/istio/istio-operator.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#604 Bump version to 1.6.14-asm.2
  asm/Kptfile
  asm/cluster/istio-operator.yaml
  asm/istiod-service.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#608 Update tag, add test
  asm/Kptfile
  scripts/asm-installer/tests/script_version_check.sh
Labels: cla: yes

#601 update the readme for release
  scripts/asm-installer/README.md
  scripts/release-asm/README.md
Labels: cla: yes

#612 fix CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#610 Staging 1.8 asm
  asm/Kptfile
  asm/istio/istio-operator.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/fake_gcloud
  scripts/asm-installer/tests/run_cli_tests
Labels: cla: yes

#607 Remove unnecessary Kpt field
  asm/Kptfile
Labels: cla: yes

#613 istio option: Remove hardcoding TrustDomainAlias for ca migration. Al…
  asm/istio/options/ca-migration-meshca.yaml
Labels: cla: yes

#614 Update repo docs
  README.md
  docs/developer-guide.md
Labels: cla: yes

#616 Set the correct namespace label on VM
  scripts/asm-installer/asm_vm
Labels: cla: yes

#617 Staging 1.9 asm
  asm/Kptfile
  scripts/asm-installer/asm_vm
Labels: cla: yes

#615 rename the install_asm to asmcli
  asmcli/.yamllint
  asmcli/Dockerfile
  asmcli/README.md
  asmcli/asm_vm
  asmcli/asmcli
  asmcli/cloudbuild-flaky.yaml
  asmcli/cloudbuild-main.yaml
  asmcli/cloudbuild-staging.yaml
  asmcli/tests/common.sh
  asmcli/tests/fake_gcloud
  asmcli/tests/fake_kubectl
  asmcli/tests/run_basic_instance_template_creation
  asmcli/tests/run_basic_suite
  asmcli/tests/run_basic_suite_managed
  asmcli/tests/run_basic_suite_required_roles
  asmcli/tests/run_basic_suite_vm
  asmcli/tests/run_cli_tests
  asmcli/tests/run_install_custom_cert_suite
  asmcli/tests/run_migration_suite_citadel
  asmcli/tests/run_migration_suite_citadel_prev
  asmcli/tests/run_migration_suite_meshca
  asmcli/tests/run_migration_suite_meshca_prev
  asmcli/tests/run_print_config_test
  asmcli/tests/script_version_check.sh
  asmcli/tests/setup_longterm_cluster
  scripts/release-asm/common.sh
  scripts/release-asm/pre_release_backfill
  scripts/release-asm/release_asm_installer
Labels: cla: yes

#620 Configure MCP to use GKE Connect
  asm/Kptfile
  asm/third-party/hub-connect-impersonate-rbac.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#621 Add timestamps if ts available and verbose mode
  scripts/asm-installer/install_asm
Labels: cla: yes

#618 integrate bazel and add the preliminary logic to merge scripts
  .gitignore
  BUILD
  WORKSPACE
  asmcli/asmcli.sh
  asmcli/cloudbuild-main.yaml
  docs/developer-guide.md
  scripts/release-asm/merge
Labels: cla: yes

#622 Retry scraping URLs if empty
  scripts/asm-installer/install_asm
Labels: cla: yes

#625 Add warning for possible uninitialized meshconfig
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#631 Change service account detection pattern
  scripts/asm-installer/install_asm
Labels: cla: yes

#640 Fix namespace validation in 1.9
  scripts/asm-installer/install_asm
Labels: asm-installer, bug, cla: yes

#633 install_asm: allow setting GCLOUD_USER_OR_SA
  scripts/asm-installer/install_asm
Labels: cla: yes

#635 NEG options
  asm/Kptfile
  asm/istio/options/ingress-neg-backendconfig.yaml
  asm/istio/options/ingress-neg.yaml
Labels: cla: yes

#636 Install istio-cni with securityContext for SELinux
  asm/istio/options/cni-selinux.yaml
Labels: cla: yes

#644 NEG options (take 2)
  asm/Kptfile
  asm/istio/options/ingress-neg-backendconfig.yaml
  asm/istio/options/ingress-neg.yaml
Labels: cla: yes

#634 intial integration of bats
  .gitignore
  BUILD
  asmcli/asmcli.sh
  asmcli/cloudbuild-main.yaml
  asmcli/tests/main_test.bats
  asmcli/tests/unit_test_common.bash
  package-lock.json
  package.json
Labels: cla: yes

#646 Version bump
  asm/Kptfile
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#648 update dev guide for writing/running tests
  docs/developer-guide.md
Labels: cla: yes

#647 Install base installation before provisioning MCP
  scripts/asm-installer/install_asm
Labels: asm-installer, bug, cla: yes

#649 updated npm info to dev-guide.md
  docs/developer-guide.md
Labels: cla: yes
