Repository GoogleCloudPlatform/anthos-service-mesh-packages, pull requests merged in 2021-06, with the labels that each got.

#708 fix: privateca istiod service account respects _CI_NO_REVISION
  scripts/asm-installer/install_asm
Labels: cla: yes

#707 add linter for global and local references
  asmcli/asmcli.sh
  asmcli/cloudbuild-main.yaml
  asmcli/components/ca/mesh-ca.sh
  asmcli/tests/lint_variables
Labels: cla: yes

#554 Add CA migration script.
  scripts/ca-migration/README.md
  scripts/ca-migration/migrate_ca
Labels: cla: yes

#712 asm_vm: prepend project id to network id
  scripts/asm-installer/asm_vm
Labels: cla: yes

#714 Update retry() to show executed command when it failed
  scripts/asm-installer/install_asm
Labels: cla: yes

#715 Remove MCP SA references
  asm/Kptfile
  asm/third-party/hub-connect-impersonate-rbac.yaml
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#711 add apply subcommand
  asmcli/asmcli.sh
  asmcli/commands/install.sh
  asmcli/commands/print-config.sh
  asmcli/commands/validate.sh
  asmcli/lib/context.sh
  asmcli/tests/lib/context.bats
Labels: cla: yes

#719 Update image to 1.10
  asm/Kptfile
  asm/istio/istio-operator.yaml
  asm/istio/options/managed-control-plane.yaml
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/release-asm/common.sh
Labels: cla: yes

#718 Update docker file
  asmcli/Dockerfile
  asmcli/cloudbuild-main.yaml
Labels: cla: yes

#722 Fix the link for redeployment in the output
  scripts/asm-installer/install_asm
Labels: cla: yes

#724 Some change for asm_vm in testing
  scripts/asm-installer/asm_vm
Labels: cla: yes

#716 transform cli tests to unit tests
  asmcli/cloudbuild-main.yaml
  asmcli/tests/fake_gcloud
  asmcli/tests/fake_kubectl
  asmcli/tests/lib/context.bats
  asmcli/tests/main_test.bats
  asmcli/tests/run_cli_tests
  asmcli/tests/unit_test_common.bash
Labels: cla: yes

#725 fix: option file for migrated meshca trustDomainAlias
  asm/Kptfile
  asm/istio/options/ca-migration-meshca.yaml
Labels: cla: yes

#734 Don't run VM tests on v2 branch
  asmcli/cloudbuild-main.yaml
Labels: cla: yes

#735 delete workloadgroup before delete namespace to prevent flaky delete issue and create new cluster to runtests
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/tests/run_basic_instance_template_creation
  scripts/asm-installer/tests/run_basic_suite_vm
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#737 Add CA migration script.
  scripts/ca-migration/README.md
  scripts/ca-migration/migrate_ca
Labels: cla: yes

#738 set trust domain aliases to include both new Hub WIP and old Hub WIP to achieve no downtime upgrade for VM
  scripts/asm-installer/install_asm
Labels: cla: yes

#709 Revert "Enable Network Policy for MCP with CNI (#668)"
  scripts/asm-installer/install_asm
Labels: cla: yes

#739 apply CPR's crd/cr
  asm/control-plane-revision/cr_rapid.yaml
  asm/control-plane-revision/cr_regular.yaml
  asm/control-plane-revision/cr_stable.yaml
  asm/control-plane-revision/crd.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#721 Support new configuration in service proxy agent
  scripts/asm-installer/Dockerfile
  scripts/asm-installer/asm_vm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#740 make --hub_meshca behavior consistent between ASM 1.9 and ASM 1.10 for GKE-on-GCP
  asm/Kptfile
  asm/istio/options/hub-meshca.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#745 transform cli tests to unit tests
  asmcli/asmcli
  asmcli/cloudbuild-main.yaml
  asmcli/tests/fake_gcloud
  asmcli/tests/fake_kubectl
  asmcli/tests/lib/context.bats
  asmcli/tests/main_test.bats
  asmcli/tests/run_cli_tests
  asmcli/tests/unit_test_common.bash
Labels: cla: yes

#747 make --hub_meshca behavior consistent between ASM 1.9 and ASM 1.10 for GKE-on-GCP
  asm/Kptfile
  asm/istio/options/hub-meshca.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#748 remove dataplane
  asm/control-plane-revision/cr_rapid.yaml
  asm/control-plane-revision/cr_regular.yaml
  asm/control-plane-revision/cr_stable.yaml
  asm/control-plane-revision/crd.yaml
Labels: cla: yes

#750 Allow staging image testing before release
  asm/istio/expansion/vm-eastwest-gateway.yaml
  scripts/asm-installer/asm_vm
Labels: cla: yes

#752 Update 1.9 image
  asm/Kptfile
  asm/istio/istio-operator.yaml
  asm/istio/options/managed-control-plane.yaml
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#751 Update 1.10 image
  asm/Kptfile
  asm/istio/expansion/vm-eastwest-gateway.yaml
  asm/istio/istio-operator.yaml
  asm/istio/options/managed-control-plane.yaml
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#753 add crd/cr files for cpr and apply them (#739)
  asm/control-plane-revision/cr_rapid.yaml
  asm/control-plane-revision/cr_regular.yaml
  asm/control-plane-revision/cr_stable.yaml
  asm/control-plane-revision/crd.yaml
  asmcli/asmcli
  asmcli/asmcli.sh
  asmcli/commands/install.sh
Labels: cla: yes

#749 add-to-mesh subcommand
  asmcli/asmcli
  asmcli/asmcli.sh
  asmcli/cloudbuild-staging.yaml
  asmcli/commands/add-to-mesh.sh
  asmcli/commands/help.sh
  asmcli/commands/install.sh
  asmcli/commands/print-config.sh
  asmcli/lib/context.sh
  asmcli/tests/lib/context.bats
  asmcli/tests/run_add_to_mesh
  asmcli/tests/setup_longterm_cluster
Labels: cla: yes

#754 Require Fleet registration with MCP
  asm/Kptfile
  scripts/asm-installer/asm_vm
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#744 Migration script
  scripts/migration/README.md
  scripts/migration/migrate-addon
Labels: cla: yes

#756 1.9.6-1
  asm/Kptfile
  asm/istio/istio-operator.yaml
  asm/istio/options/managed-control-plane.yaml
  asm/third-party/hub-connect-impersonate-rbac.yaml
  scripts/asm-installer/asm_vm
  scripts/asm-installer/cloudbuild-flaky.yaml
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
Labels: cla: no

#759 Bump rev
  asm/Kptfile
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#761 Update citadel and off-gcp overlays for multicloud support
  asm/istio/options/citadel-ca.yaml
  asm/istio/options/off-gcp.yaml
Labels: cla: yes

#764 fix context append
  asmcli/asmcli
  asmcli/commands/install.sh
Labels: cla: yes

#760 install remote secrets on the clusters
  BUILD
  asmcli/asmcli
  asmcli/commands/add-to-mesh.sh
  asmcli/lib/context.sh
  asmcli/tests/main_test.bats
  asmcli/tests/unit_test_common.bash
Labels: cla: yes

#765 Add option to skip default gateway installation.
  asm/istio/options/no-default-ingress.yaml
Labels: asm-installer, cla: yes

#766 Add multicloud support
  asmcli/asmcli
  asmcli/asmcli.sh
  asmcli/commands/install.sh
  asmcli/commands/print-config.sh
  asmcli/commands/validate.sh
  asmcli/lib/util.sh
  asmcli/tests/lib/util.bats
Labels: cla: yes

#768 Test faster
  BUILD
Labels: cla: yes

#767 rename add-to-mesh subcommand
  asmcli/asmcli
  asmcli/asmcli.sh
  asmcli/cloudbuild-staging.yaml
  asmcli/commands/create-mesh.sh
  asmcli/commands/help.sh
  asmcli/lib/util.sh
  asmcli/tests/main_test.bats
  asmcli/tests/run_create_mesh
  asmcli/tests/setup_longterm_cluster
Labels: cla: yes

#770 update the linter to run through each file
  BUILD
  asmcli/asmcli
  asmcli/cloudbuild-main.yaml
  asmcli/commands/create-mesh.sh
  asmcli/tests/lint_variables
Labels: cla: yes

#771 Adding TrustDomain Alias to scriptaro based on option
  scripts/asm-installer/install_asm
Labels: cla: yes

#774 Download kpt when necessary
  scripts/asm-installer/Dockerfile
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
Labels: cla: yes

#763 1.4 migration : Use MCP rapid channel
  scripts/migration/migrate-addon
Labels: cla: yes

#773 Bump version
  asm/Kptfile
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes
