Repository GoogleCloudPlatform/anthos-service-mesh-packages, pull requests merged in 2021-01, with the labels that each got.

#344 Properly label namespaces in migration tests
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_migration_suite_citadel
  scripts/asm-installer/tests/run_migration_suite_citadel_prev
  scripts/asm-installer/tests/run_migration_suite_meshca
  scripts/asm-installer/tests/run_migration_suite_meshca_prev
Labels: asm-installer, bug

#349 Include multicluster profile all the time
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
Labels: asm-installer, bug

#357 Fix outro logic
  scripts/asm-installer/install_asm
Labels: asm-installer, bug

#351 Apply validation fix before installation
  scripts/asm-installer/cloudbuild.yaml
  scripts/asm-installer/install_asm
Labels: asm-installer

#361 Add -e flag to error messages.
  scripts/asm-installer/install_asm
Labels: asm-installer, enhancement

#356 Allow asm installer to prepare VM setup
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_suite_vm
Labels: asm-installer, enhancement

#370 Change one test to use long term cluster
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_suite
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#373 Fix CEL expression by adding quote around email
  asm/identity-provider/googleidp.yaml
Labels: cla: yes

#372 Avoid VM env var override
  asm/istio/options/hub-meshca.yaml
Labels: cla: yes

#374 [VM Script] Update VM Script to be consistent with ASM installer
  asm/vm/install_asm_vm
Labels: cla: yes

#381 Merge all profiles, force empty profile
  asm/Kptfile
  asm/istio/istio-operator.yaml
  asm/istio/options/multicluster.yaml
  asm/istio/options/multiproject.yaml
  asm/istio/options/prometheus.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
  scripts/asm-installer/tests/run_print_config_test
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#382 Relax validation constraints
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
Labels: cla: yes

#383 unique name for clusterrolebinding
  scripts/asm-installer/install_asm
Labels: cla: yes

#378 Rebase master-prow on master
  scripts/asm-installer/install_asm
Labels: cla: yes

#375 Capitalize gcloud query AND
  scripts/asm-installer/install_asm
Labels: cla: yes

#376 Install canonical service controller with managed control plane
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#379 More flexible logic for Environ config
  scripts/asm-installer/install_asm
Labels: cla: yes
