Repository GoogleCloudPlatform/anthos-service-mesh-packages, pull requests merged in 2021-03, with the labels that each got.

#510 Default CA properly on upgrade
  scripts/asm-installer/install_asm
Labels: asm-installer, bug, cla: yes

#511 Better error message on missing nc
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#512 Move custom cert test to flaky tests
  scripts/asm-installer/cloudbuild-flaky.yaml
  scripts/asm-installer/cloudbuild-master.yaml
Labels: cla: yes

#513 Symlink istioctl binary, clarify MCP outro
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#514 Bump rc
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#515 Include directions for upgrating validation fix on upgrade/migration
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_migration_suite_meshca
Labels: asm-installer, cla: yes

#517 Update service proxy agent image version
  scripts/asm-installer/asm_vm
Labels: cla: yes

#518 Add BSD csplit compatibility (#449)
  scripts/asm-installer/install_asm
Labels: asm-installer, bug, cla: yes

#519 Add release-1.9-asm into release script.
  scripts/asm-installer/release_asm_installer
Labels: cla: yes

#520 set ISTIO_META_CLUSTER_ID in metadata
  scripts/asm-installer/asm_vm
Labels: cla: yes

#521 use fetched cluster id in meta
  scripts/asm-installer/asm_vm
Labels: cla: yes

#523 Clean up on unused folders
  asm/Kptfile
  asm/cluster/cluster.yaml
  asm/cluster/nodepool.yaml
  asm/istio/istio-operator.yaml
  asm/project/enable-services.yaml
  kustomize-functions/validate-asm/LICENSE_TEMPLATE
  kustomize-functions/validate-asm/Makefile
  kustomize-functions/validate-asm/README.md
  kustomize-functions/validate-asm/image/Dockerfile
  kustomize-functions/validate-asm/image/go.mod
  kustomize-functions/validate-asm/image/go.sum
  kustomize-functions/validate-asm/image/main.go
  kustomize-functions/validate-asm/local-resource/example-use.yaml
Labels: cla: yes

#525 Remove the cnrm qualification framwork configs.
  cloudbuild.yaml
  id_rsa.enc
  known_hosts
Labels: cla: yes

#524 Release 1.8 asm
  asm/Kptfile
  scripts/asm-installer/install_asm
Labels: cla: yes

#526 vm eastwest iop should not have name
  asm/istio/options/vm.yaml
Labels: cla: yes

#528 Allow custom revisions for VM workloads
  scripts/asm-installer/asm_vm
Labels: cla: yes

#516 Modifying asm installer script to add support for custom revision tag.
  asm/istio/options/trustanchor-meshca.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_basic_suite
Labels: cla: yes

#531 Upgrade ASM in Anthos Sample Deployment to 1.9.0-asm.3
  asm/Kptfile
  asm/istio/istio-operator.yaml
Labels: cla: yes

#532 Fail when --custom-overlay passed with --managed
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
Labels: cla: yes

#534 Backport revisioned ingressgateways to 17
  asm/Kptfile
  asm/istio/options/revisioned-custom-ingressgateway.yaml
  asm/istio/options/revisioned-istio-ingressgateway.yaml
Labels: cla: yes

#535 Upgrade ASM in Anthos Sample Deployment to 1.9.0-asm.3
  asm/istio/istio-operator.yaml
Labels: cla: yes

#537 Anthos sample deployment
  asm/Kptfile
  asm/istio/istio-operator.yaml
Labels: cla: yes

#542 Properly validate commands in compatibility vars
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
Labels: asm-installer, bug, cla: yes

#543 Only override boot disk name when creating instance template
  scripts/asm-installer/asm_vm
Labels: cla: yes

#544 Add proper SemVer support
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes, enhancement

#545 All installations should have GKE WI enabled
  scripts/asm-installer/install_asm
Labels: cla: yes

#546 Don't overwrite configuration from a different version
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes, enhancement

#547 Refactor release script
  scripts/asm-installer/release_asm_installer
Labels: cla: yes

#548 Require workload identity before environ registration
  scripts/asm-installer/install_asm
Labels: cla: yes

#549 VM script should fail when service accounts mismatch
  scripts/asm-installer/asm_vm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#550 Check tags when releasing install_asm
  scripts/asm-installer/asm_vm
  scripts/asm-installer/release_asm_installer
Labels: cla: yes

#555 Add logging writer role to list of MCP SA required perms
  scripts/asm-installer/install_asm
Labels: cla: yes

#557 Always pull the service proxy with matching version
  scripts/asm-installer/asm_vm
Labels: cla: yes

#541 enable asm vm to check the image distro
  scripts/asm-installer/asm_vm
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_instance_template_creation
Labels: cla: yes

#558 Add region tags around required_iam_roles
  scripts/asm-installer/install_asm
Labels: cla: yes

#559 Don't enable cross-cluster workload entries by default
  asm/istio/istio-operator.yaml
Labels: cla: yes

#561 Don't enable cross-cluster workload entries for environ clusters
  asm/istio/options/hub-meshca.yaml
Labels: cla: yes

#565 Istio GKE addon 1.4 to 1.6 migration script
  scripts/migration/README.md
  scripts/migration/upgrade-14-16
Labels: cla: yes

#567 Staging 1.7 asm
  asm/Kptfile
  asm/istio/options/revisioned-custom-ingressgateway.yaml
  asm/istio/options/revisioned-istio-ingressgateway.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#571 Change how to retrieve environ project id
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes
