Repository GoogleCloudPlatform/anthos-service-mesh-packages, pull requests merged in 2021-11, with the labels that each got.

#1033 use v1beta1 for CPR CR
  asm/control-plane-revision/cr_rapid.yaml
  asm/control-plane-revision/cr_rapid_reconciled.yaml
  asm/control-plane-revision/cr_regular.yaml
  asm/control-plane-revision/cr_regular_reconciled.yaml
  asm/control-plane-revision/cr_stable.yaml
  asm/control-plane-revision/cr_stable_reconciled.yaml
  asm/control-plane-revision/crd.yaml
Labels: cla: yes

#1035 Update migrate-addon script
  scripts/migration/migrate-addon
Labels: cla: yes

#1036 Handle re-use of output_dir across configuration settings
  asmcli/asmcli
  asmcli/asmcli.sh
  asmcli/commands/create-mesh.sh
  asmcli/lib/util.sh
Labels: bug, asm-installer, cla: yes

#1037 Parse info from membership sometimes
  asmcli/asmcli
  asmcli/lib/checks.sh
Labels: bug, asm-installer, cla: yes

#1038 Use proper configmap name for trust domain logic
  asmcli/asmcli
  asmcli/commands/create-mesh.sh
  asmcli/components/ca/mesh-ca.sh
Labels: bug, asm-installer, cla: yes

#1040 create cross-project mesh service account
  asmcli/asmcli
  asmcli/lib/installation_dependencies.sh
  asmcli/lib/util.sh
Labels: cla: yes

#1046 Migrate ValidatingWebhookConfiguration to v1
  asm/istio/options/managed-control-plane-webhooks.yaml
Labels: cla: yes

#1047 Migrate ValidatingWebhookConfiguration to v1 (#1046)
  asm/istio/options/managed-control-plane-webhooks.yaml
Labels: cla: yes

#1049 Allow passing in base rel path for CI
  asmcli/asmcli
  asmcli/asmcli.sh
  asmcli/lib/util.sh
Labels: asm-installer, cla: yes

#1050 Add --enable-meshconfig-init flag to asmcli
  asmcli/asmcli
  asmcli/commands/help.sh
  asmcli/components/control-plane/in-cluster.sh
  asmcli/components/control-plane/managed.sh
  asmcli/lib/checks.sh
  asmcli/lib/context.sh
  asmcli/lib/parse.sh
Labels: cla: yes

#1051 Migrate ClusterRole to v1
  asm/canonical-service/controller.yaml
Labels: cla: yes

#1052 Migrate ClusterRole to v1
  asm/canonical-service/controller.yaml
Labels: cla: yes

#1045 move afc install to main command
  asmcli/asmcli
  asmcli/cloudbuild-main.yaml
  asmcli/commands/help.sh
  asmcli/commands/install.sh
  asmcli/commands/validate.sh
  asmcli/components/control-plane/managed.sh
  asmcli/lib/checks.sh
  asmcli/lib/config.sh
  asmcli/lib/context.sh
  asmcli/lib/parse.sh
  asmcli/lib/util.sh
  asmcli/lib/validate.sh
  asmcli/tests/run_basic_suite_managed_legacy
Labels: cla: yes

#1056 Update version to 1.12
  asm/Kptfile
  asmcli/asmcli
  asmcli/asmcli.sh
Labels: cla: yes

#1059 only provision one channel at a time for MCP
  asmcli/asmcli
  asmcli/lib/util.sh
  asmcli/tests/lib/util.bats
Labels: cla: yes

#1061 Update warning message for gateway override
  asmcli/asmcli
  asmcli/lib/validate.sh
Labels: cla: yes

#1053 Support new resourcelink format
  scripts/migration/migrate-to-asm
Labels: cla: yes

#1055 allow adding arbitrary args for hub registration
  asmcli/asmcli
  asmcli/lib/context.sh
  asmcli/lib/installation_dependencies.sh
Labels: cla: yes

#1058 Disable in-cluster canonical service
  asmcli/asmcli
  asmcli/commands/install.sh
Labels: cla: yes

#1060 Add created-by label to CPRs
  asm/Kptfile
  asm/control-plane-revision/cr_rapid.yaml
  asm/control-plane-revision/cr_regular.yaml
  asm/control-plane-revision/cr_stable.yaml
  asmcli/asmcli
  asmcli/commands/experimental/install.sh
  asmcli/lib/config.sh
Labels: cla: yes

#1062 Add missing wrapper function
  scripts/migration/migrate-to-asm
Labels: cla: yes
