Repository GoogleCloudPlatform/anthos-service-mesh-packages, pull requests merged in 2021-02, with the labels that each got.

#384 Clean up old namespaces on setup
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#380 Change install tests to use long term cluster
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_suite
  scripts/asm-installer/tests/run_basic_suite_managed
  scripts/asm-installer/tests/run_basic_suite_vm
  scripts/asm-installer/tests/run_install_custom_cert_suite
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#386 Add config for MCP validatingwebhook
  asm/Kptfile
  asm/istio/options/managed-control-plane-webhooks.yaml
Labels: cla: yes

#387 Unify the install entry returned by istioctl_path
  scripts/asm-installer/install_asm
Labels: cla: yes

#385 Bump version
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/fake_gcloud
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#389 Install base client-side for MCP
  asm/Kptfile
  asm/istio/istio-operator.yaml
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#391 Fix bad merge and readd yaml
  asm/istio/options/multicloud.yaml
  asm/istio/options/multicluster.yaml
  asm/istio/options/multiproject.yaml
Labels: cla: yes

#388 Revision based istio-ingressgateway
  asm/Kptfile
  asm/istio/options/revisioned-istio-ingressgateway.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#390 1.8.2
  asm/Kptfile
  asm/identity-provider/googleidp.yaml
  asm/istio/istio-operator.yaml
  asm/istio/options/hub-meshca.yaml
  asm/istio/options/managed-control-plane-webhooks.yaml
  asm/istio/options/prometheus.yaml
  asm/istio/options/revisioned-istio-ingressgateway.yaml
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/fake_gcloud
  scripts/asm-installer/tests/run_basic_suite
  scripts/asm-installer/tests/run_basic_suite_managed
  scripts/asm-installer/tests/run_cli_tests
  scripts/asm-installer/tests/run_install_custom_cert_suite
  scripts/asm-installer/tests/run_print_config_test
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#392 Check existence of membership object before getting it
  scripts/asm-installer/install_asm
Labels: cla: yes

#394 Add setter for managed control plane
  asm/Kptfile
Labels: cla: yes

#396 Add setter for managed control plane (#394)
  asm/Kptfile
Labels: cla: yes

#393 Add CLOUDRUN_ADDR for managed control plane
  asm/istio/options/managed-control-plane.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#398 Publish master branch to install_asm_unstable
  scripts/asm-installer/release_asm_installer
Labels: cla: yes

#399 Add CLOUDRUN_ADDR for managed control plane (#393)
  asm/istio/options/managed-control-plane.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#397 Add more CRD checks
  scripts/asm-installer/install_asm
Labels: cla: yes

#401 Add more CRD checks (#397)
  scripts/asm-installer/install_asm
Labels: cla: yes

#403 Overwrite final config when reusing output directory
  scripts/asm-installer/install_asm
Labels: cla: yes

#405 Work around istioctl bug with multi component yaml files
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_print_config_test
Labels: cla: yes

#406 Remove --force-conflicts flag
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#408 Work around istioctl bug with multi component yaml files (#405)
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_print_config_test
Labels: asm-installer, bug, cla: yes

#409 Not to apply istiod svc when _CI_NO_REVISION=1
  scripts/asm-installer/install_asm
Labels: cla: yes

#412 Not to apply istiod svc when _CI_NO_REVISION=1
  scripts/asm-installer/install_asm
Labels: cla: yes

#413 Allow cluster to be registered in a different project
  scripts/asm-installer/install_asm
Labels: cla: yes

#414 Detect service account better
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/fake_gcloud
  scripts/asm-installer/tests/run_cli_tests
Labels: asm-installer, bug, cla: yes

#416 Wrap commands better
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#417 Enable specifying alpha builds for testing
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#402 [VM Script] Update create instance template logic
  asm/vm/asm_vm
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_instance_template_creation
  scripts/asm-installer/tests/run_basic_suite_vm
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#426 Don't register with the --enable-all flag
  scripts/asm-installer/install_asm
Labels: asm-installer, bug, cla: yes

#428 Remove VM suite from master pre-submit tests
  scripts/asm-installer/cloudbuild-master.yaml
Labels: cla: yes

#427 Use less permissions for MCP SA
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#429 Add support for custom ingressgateway
  asm/Kptfile
  asm/istio/options/revisioned-custom-ingressgateway.yaml
Labels: cla: yes

#430 [VM Script] Allow users to specify a proxy agent
  asm/vm/asm_vm
Labels: cla: yes

#432 Fix seperator issue in trusted_gcp_project when only 1 trusted_gcp_pr…
  scripts/asm-installer/install_asm
Labels: cla: yes

#433 Fix seperator issue in trusted_gcp_project when only 1 trusted_gcp_pr…
  scripts/asm-installer/install_asm
Labels: cla: yes

#434 Fix option flags being ignored issue when reinstalling on an existing folder
  scripts/asm-installer/install_asm
Labels: cla: yes

#418 Use less privileged operations during validation
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/fake_kubectl
  scripts/asm-installer/tests/run_cli_tests
Labels: cla: yes

#437 Publish staging versions of install_asm
  scripts/asm-installer/release_asm_installer
Labels: asm-installer, cla: yes

#435 Fix option flags being ignored issue when reinstalling on an existing…
  scripts/asm-installer/install_asm
Labels: cla: yes

#438 Remove the dependency on metadata server
  asm/istio/istio-operator.yaml
Labels: cla: yes

#440 Setup different cluster for environ-based installations
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#441 Allow revisioned istiod to be exposed for discovery
  asm/Kptfile
  asm/istio/expansion/expose-istiod.yaml
Labels: cla: yes

#444 [VM Script] Allow CI to use different image tag
  asm/vm/asm_vm
Labels: cla: yes

#443 Enable new auth for managed control plane gateway
  asm/istio/options/managed-control-plane.yaml
Labels: cla: yes

#447 Always override default kpt tag
  scripts/asm-installer/install_asm
Labels: cla: yes

#439 Remove the dependency on metadata server (#438)
  asm/istio/istio-operator.yaml
Labels: cla: yes

#451 Keep long term cluster registration
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#454 Do not block validation on asmv label
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/fake_gcloud
Labels: asm-installer, cla: yes

#455 Bump version to 1.6.14-asm.1
  asm/Kptfile
  asm/cluster/istio-operator.yaml
  asm/istiod-service.yaml
  scripts/asm-installer/cloudbuild-staging.yaml
  scripts/asm-installer/install_asm
Labels: cla: yes

#458 Don't delete everything in release branch
  scripts/asm-installer/cloudbuild-staging.yaml
Labels: cla: yes

#449 Add BSD csplit compatibility
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes, enhancement

#442 Conditionally require APIs for CA
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_basic_suite_managed
Labels: asm-installer, bug, cla: yes

#461 [VM Script] Make use of some install_asm functions
  asm/vm/asm_vm
Labels: cla: yes

#457 enable cross cluster workload entry reading by default
  asm/istio/istio-operator.yaml
  asm/istio/options/hub-meshca.yaml
Labels: cla: yes

#446 [VM Script] Add revisioned Istiod support
  asm/vm/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#452 Check existence of membership CR
  asm/vm/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#424 [VM Script] Add more tests
  asm/vm/asm_vm
  scripts/asm-installer/cloudbuild-flaky.yaml
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_instance_template_creation
Labels: cla: yes

#465 Staging 1.8 asm
  asm/istio/istio-operator.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/fake_gcloud
  scripts/asm-installer/tests/fake_kubectl
  scripts/asm-installer/tests/run_cli_tests
Labels: asm-installer, cla: yes

#468 First RC build for 1.9
  scripts/asm-installer/install_asm
Labels: cla: yes

#470 [VM Script] Update version
  asm/vm/asm_vm
Labels: cla: yes

#471 Move vm tests to flaky tests
  scripts/asm-installer/cloudbuild-flaky.yaml
  scripts/asm-installer/cloudbuild-master.yaml
Labels: cla: yes

#473 Do not exclude startup-script in metadata
  asm/vm/asm_vm
Labels: cla: yes

#463 Enable service mesh feature
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_instance_template_creation
  scripts/asm-installer/tests/run_basic_suite_vm
Labels: cla: yes

#467 [VM Script] Add default istiod service name resolution
  asm/vm/asm_vm
Labels: cla: yes

#474 Use client side apply for CRD installation of MCP
  scripts/asm-installer/install_asm
Labels: cla: yes

#477 Stop using staging endpoint for managed control plane test
  scripts/asm-installer/tests/run_basic_suite_managed
Labels: cla: yes

#472 dont set default revision in meta
  asm/vm/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#460 [VM Script]Prepare cluster for VM workloads
  asm/istio/expansion/README.md
  asm/istio/expansion/vm-eastwest-gateway.yaml
  asm/vm/asm_vm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#478 handle default revision when fetching config map
  asm/vm/asm_vm
Labels: cla: yes

#481 Move asm_vm script
  asm/vm/README.md
  scripts/asm-installer/README.md
  scripts/asm-installer/asm_vm
  scripts/asm-installer/cloudbuild-flaky.yaml
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/release_asm_installer
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#482 Don't register with -e unless using a feature that requires it
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
Labels: cla: yes

#483 Fix release script, add very basic check
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/release_asm_installer
Labels: cla: yes

#484 Avoid hosts file being reconciled
  scripts/asm-installer/asm_vm
Labels: cla: yes

#485 Modify asm_vm success message
  scripts/asm-installer/asm_vm
Labels: cla: yes

#486 Make --print-config compatible with --managed
  scripts/asm-installer/install_asm
Labels: cla: yes

#488 Switch to staging meshconfig API for managed control plane
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_suite_managed
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#487 Print flashy message when using tmp directory
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#489 Merge Staging 1.8 asm to release-1.8-asm (#465)
  asm/istio/istio-operator.yaml
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/fake_gcloud
  scripts/asm-installer/tests/fake_kubectl
  scripts/asm-installer/tests/run_basic_suite_managed
  scripts/asm-installer/tests/run_cli_tests
  scripts/asm-installer/tests/setup_longterm_cluster
Labels: cla: yes

#491 Update istiod routing config
  asm/Kptfile
  asm/istio/expansion/expose-istiod.yaml
Labels: cla: yes

#492 Script changes to correct istiod routing
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: cla: yes

#494 Move MCP test back to normal config
  scripts/asm-installer/cloudbuild-flaky.yaml
  scripts/asm-installer/cloudbuild-master.yaml
Labels: asm-installer, cla: yes

#495 Print the version at the end of installation
  scripts/asm-installer/install_asm
Labels: cla: yes

#490 Improve node pool validation
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_cli_tests
Labels: asm-installer, bug, cla: yes

#493 Add yamllint, fix errors
  asm/cluster/cluster.yaml
  asm/cluster/nodepool.yaml
  asm/identity-provider/identityprovider-crd.yaml
  asm/istio/expansion/expose-istiod.yaml
  asm/istio/expansion/expose-services.yaml
  asm/istio/expansion/vm-eastwest-gateway.yaml
  asm/istio/istio-operator.yaml
  asm/istio/istiod-service.yaml
  asm/istio/options/audit-authorizationpolicy.yaml
  asm/istio/options/citadel-ca.yaml
  asm/istio/options/cloud-tracing.yaml
  asm/istio/options/cni-gcp.yaml
  asm/istio/options/cni-onprem.yaml
  asm/istio/options/egressgateways.yaml
  asm/istio/options/envoy-access-log.yaml
  asm/istio/options/hub-meshca.yaml
  asm/istio/options/iap-operator.yaml
  asm/istio/options/internal-load-balancer.yaml
  asm/istio/options/managed-control-plane-webhooks.yaml
  asm/istio/options/managed-control-plane.yaml
  asm/istio/options/multicloud.yaml
  asm/istio/options/multicluster.yaml
  asm/istio/options/multiproject.yaml
  asm/istio/options/private-ca.yaml
  asm/istio/options/prometheus.yaml
  asm/istio/options/revisioned-custom-ingressgateway.yaml
  asm/istio/options/revisioned-istio-ingressgateway.yaml
  asm/istio/options/v1beta1-crds.yaml
  asm/istio/options/vm.yaml
  asm/project/enable-services.yaml
  scripts/asm-installer/.yamllint
  scripts/asm-installer/Dockerfile
  scripts/asm-installer/cloudbuild-master.yaml
Labels: cla: yes

#497 Use new RC
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#496 Fix ordering bug when working around a different bug
  scripts/asm-installer/install_asm
Labels: asm-installer, bug, cla: yes

#500 Fix failing VM test
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#498 Don't install the gateway on ASM installations with MCP
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes

#502 Save generated kubeconfig, create OUTPUT_DIR when safe to do so
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/run_print_config_test
Labels: asm-installer, cla: yes

#503 Use production meshconfig API for MCP
  scripts/asm-installer/tests/common.sh
  scripts/asm-installer/tests/run_basic_suite_managed
Labels: cla: yes

#504 Move vm test to master test job
  scripts/asm-installer/cloudbuild-flaky.yaml
  scripts/asm-installer/cloudbuild-master.yaml
Labels: cla: yes

#501 Don't patch validating webhook when provisioning managed control plane
  asm/istio/options/managed-control-plane-webhooks.yaml
  scripts/asm-installer/install_asm
Labels: asm-installer, cla: yes

#505 Update default service proxy agent address
  scripts/asm-installer/asm_vm
Labels: cla: yes

#506 Add a version check of scripts
  scripts/asm-installer/cloudbuild-master.yaml
  scripts/asm-installer/tests/script_version_check.sh
Labels: cla: yes

#508 Add GKE WP enablement condition for unmanaged ASM
  scripts/asm-installer/install_asm
Labels: cla: yes

#499 Add newline to vm option file
  asm/istio/options/vm.yaml
Labels: cla: yes

#507 Align MCP gateway image and hub with ASM unmanaged
  asm/istio/options/managed-control-plane.yaml
Labels: cla: yes

#509 Bump everything to latest rc
  asm/Kptfile
  asm/istio/istio-operator.yaml
  asm/istio/options/managed-control-plane.yaml
  scripts/asm-installer/asm_vm
  scripts/asm-installer/install_asm
  scripts/asm-installer/tests/common.sh
Labels: cla: yes
